name: linting, testing, building
run-name: Running GitHub Actions 🚀
on:
  push:
    branches: [master]
  pull_request:
    branches:
      [master]
jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install
      - name: create production project build
        if: always()
        run: npm run build:prod
      - name: lint typescript
        if: always()
        run: npm run lint:ts
      - name: lint css
        if: always()
        run: npm run lint:scss
      - name: unit testing
        if: always()
        run: npm run test:unit
      - name: build storybook
        if: always()
        run: npm run storybook:build
      - name: regress screenshot loki testing + storybook
        if: always()
        run: npm run test:ui:ci
